---
- hosts: localhost
  become: yes
  tasks:
  - name: create ansible ubuntu nodes
    ec2:
      key_name: MyTomcat
      instance_type: t2.micro
      image: ami-0975f215b07bf47b1
      wait: yes
      group: sg-00c29cea38da34ced
      region: us-east-2
      count: 2
      vpc_subnet_id: subnet-e6ae8baa
      assign_public_ip: yes
      instance_tags:
        Name: myAnsibleUbuntuNode