---
- hosts: localhost
  become: yes
  tasks:
  - name: create ansible ubuntu nodes
    ec2:
      key_name: MyTomcat
      instance_type: t2.micro
      image: ami-084528582e3ec170c
      wait: yes
      group: launch-wizard-3
      region: us-east-2
      count: 2
      vpc_subnet_id: subnet-74f87f1f
      assign_public_ip: yes
      instance_tags:
        Name: myAnsibleUbuntuNode