---
- hosts: 172.31.33.46
  become: yes
  tasks:
  - include_tasks: file.yml

  - name: i want to install webserver on ubuntu node
    apt:
      name: apache2
      state: present

  - name: i want to start webserver on ubuntu node
    service:
      name: apache2
      state: started
    notify: restartwebserver

  - name: i want to copy myindex.j2 into nodeside
    template:
      src: myindex.j2
      dest: /var/www/html/index.html
    notify: restartwebserver
  handlers:
  - name: restartwebserver
    service:
      name: apache2
      state: restarted
