---
- hosts: mywebserver
  become: yes
  tasks:
  - name: i want to install webserver on debian node only
    apt:
      name: "{{mywebpackageforubnutu}}"
      state: present
    when: ansible_os_family =="Debian"
    
  - name: I want to start webserver on debian
    service:
      name: "{{mywebpackageforubnutu}}"
      state: started
    when: ansible_os_family =="Debian"
    
  - name: i want to install webserver on redhat node only
    yum:
      name: "{{mywebpackageforredhat}}"
      state: present
    when: ansible_os_family =="RedHat"

  - name: I want to start webserver on redhat
    service:
      name: "{{mywebpackageforredhat}}"
      state: started
    when: ansible_os_family =="RedHat"

