---
- name:  Configure Tomcat user
  template:
    src:  templates/tomuser.j2
    dest: /opt/tomcat/conf/tomcat-users.xml


- name:  Configure Tomcat  context file
  template:
    src: templates/tomcontext.j2
    dest: /opt/tomcat/webapps/manager/META-INF/context.xml

- name: Configure Tomcat host-manager context file
  template:
    src: templates/tomhostcontext.j2
    dest: /opt/tomcat/webapps/host-manager/META-INF/context.xml